const jobOpenings = [
  {
    brandLogo: "https://logo.clearbit.com/google.com",
    companyName: "Google",
    datePosted: "5 days ago",
    postType: "Full-Time",
    level: "Senior Level",
    payPerHour: 85,
    location: "Mountain View, USA",
  },
  {
    brandLogo: "https://logo.clearbit.com/meta.com",
    companyName: "Meta",
    datePosted: "10 weeks ago",
    postType: "Part-Time",
    level: "Junior Level",
    payPerHour: 55,
    location: "Menlo Park, USA",
  },
  {
    brandLogo: "https://logo.clearbit.com/apple.com",
    companyName: "Apple",
    datePosted: "2 weeks ago",
    postType: "Full-Time",
    level: "Senior Level",
    payPerHour: 95,
    location: "Cupertino, USA",
  },
  {
    brandLogo: "https://logo.clearbit.com/amazon.com",
    companyName: "Amazon",
    datePosted: "3 days ago",
    postType: "Full-Time",
    level: "Junior Level",
    payPerHour: 60,
    location: "Seattle, USA",
  },
  {
    brandLogo: "https://logo.clearbit.com/netflix.com",
    companyName: "Netflix",
    datePosted: "1 week ago",
    postType: "Part-Time",
    level: "Senior Level",
    payPerHour: 80,
    location: "Los Gatos, USA",
  },
  {
    brandLogo: "https://logo.clearbit.com/microsoft.com",
    companyName: "Microsoft",
    datePosted: "4 days ago",
    postType: "Full-Time",
    level: "Senior Level",
    payPerHour: 90,
    location: "Redmond, USA",
  },
  {
    brandLogo: "https://logo.clearbit.com/tesla.com",
    companyName: "Tesla",
    datePosted: "6 weeks ago",
    postType: "Part-Time",
    level: "Junior Level",
    payPerHour: 50,
    location: "Austin, USA",
  },
  {
    brandLogo: "https://logo.clearbit.com/openai.com",
    companyName: "OpenAI",
    datePosted: "2 days ago",
    postType: "Full-Time",
    level: "Senior Level",
    payPerHour: 110,
    location: "San Francisco, USA",
  },
  {
    brandLogo: "https://logo.clearbit.com/samsung.com",
    companyName: "Samsung",
    datePosted: "3 weeks ago",
    postType: "Full-Time",
    level: "Junior Level",
    payPerHour: 45,
    location: "Seoul, South Korea",
  },
  {
    brandLogo: "https://logo.clearbit.com/nvidia.com",
    companyName: "Nvidia",
    datePosted: "8 days ago",
    postType: "Part-Time",
    level: "Senior Level",
    payPerHour: 120,
    location: "Santa Clara, USA",
  }
];

export { jobOpenings };
